name: Continuous Integration and Delivery with Github Actions
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download updated code from branch
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3.6.0
        with:
          username: '${{secrets.DOCKER_USERNAME}}'
          password: '${{secrets.DOCKER_ACCESS_TOKEN}}'

      - name: Setup Java JDK
        uses: actions/setup-java@v5.0.0
        with:
          java-version: '21'
          distribution: temurin
          cache: maven

      - name: Build Application JAR
        working-directory: ./
        run: mvn clean package

      - name: Docker Compose build
        run: docker compose build

      - name: Push to Docjer Hub Container Registry
        run: |
          docker tag ${{secrets.DOCKER_USERNAME}}/rest-erudio:latest ${{secrets.DOCKER_USERNAME}}/rest-erudio:${{github.run_id}}
          docker push ${{secrets.DOCKER_USERNAME}}/rest-erudio:latest
          docker push ${{secrets.DOCKER_USERNAME}}/rest-erudio:${{github.run_id}}